//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spin.xLenguage.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spin.xLenguage.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data concurrency conflict.
        /// </summary>
        public static string Db_Concurrency {
            get {
                return ResourceManager.GetString("Db_Concurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate value in the database.
        /// </summary>
        public static string Db_Duplicate {
            get {
                return ResourceManager.GetString("Db_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General database error.
        /// </summary>
        public static string Db_Error {
            get {
                return ResourceManager.GetString("Db_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference error, invalid foreign key.
        /// </summary>
        public static string Db_Reference {
            get {
                return ResourceManager.GetString("Db_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors Invalid File Extension.
        /// </summary>
        public static string Errors_InvalidFileExtension {
            get {
                return ResourceManager.GetString("Errors_InvalidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors Invalid Mime Type.
        /// </summary>
        public static string Errors_InvalidMimeType {
            get {
                return ResourceManager.GetString("Errors_InvalidMimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you do not have access to the system.
        /// </summary>
        public static string Generic_AccessDenied {
            get {
                return ResourceManager.GetString("Generic_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve authenticated user&apos;s email.
        /// </summary>
        public static string Generic_AuthEmailFail {
            get {
                return ResourceManager.GetString("Generic_AuthEmailFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve user identifier.
        /// </summary>
        public static string Generic_AuthIdFail {
            get {
                return ResourceManager.GetString("Generic_AuthIdFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be logged in to access this resource.
        /// </summary>
        public static string Generic_AuthRequired {
            get {
                return ResourceManager.GetString("Generic_AuthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve user role.
        /// </summary>
        public static string Generic_AuthRoleFail {
            get {
                return ResourceManager.GetString("Generic_AuthRoleFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The corporation you are trying to access is inactive, Please contact the system administrator.
        /// </summary>
        public static string Generic_CorporationInactive {
            get {
                return ResourceManager.GetString("Generic_CorporationInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already associated with another account.
        /// </summary>
        public static string Generic_EmailAlreadyUsed {
            get {
                return ResourceManager.GetString("Generic_EmailAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General exception with no specific cause.
        /// </summary>
        public static string Generic_Exception {
            get {
                return ResourceManager.GetString("Generic_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed or invalid request.
        /// </summary>
        public static string Generic_Http_BadRequest {
            get {
                return ResourceManager.GetString("Generic_Http_BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find what you were looking for.
        /// </summary>
        public static string Generic_IdNotFound {
            get {
                return ResourceManager.GetString("Generic_IdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string Generic_InvalidCredentials {
            get {
                return ResourceManager.GetString("Generic_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There seems to be an issue with the information provided.
        /// </summary>
        public static string Generic_InvalidId {
            get {
                return ResourceManager.GetString("Generic_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with the data submitted.
        /// </summary>
        public static string Generic_InvalidModel {
            get {
                return ResourceManager.GetString("Generic_InvalidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to access a null value.
        /// </summary>
        public static string Generic_NullException {
            get {
                return ResourceManager.GetString("Generic_NullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your plan has expired, please renew your account.
        /// </summary>
        public static string Generic_PlanExpired {
            get {
                return ResourceManager.GetString("Generic_PlanExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record was deleted, but the image was not removed.
        /// </summary>
        public static string Generic_RecordDeletedNoImage {
            get {
                return ResourceManager.GetString("Generic_RecordDeletedNoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems finding the specified record.
        /// </summary>
        public static string Generic_RegisterNotFound {
            get {
                return ResourceManager.GetString("Generic_RegisterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Success.
        /// </summary>
        public static string Generic_Success {
            get {
                return ResourceManager.GetString("Generic_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please try again later.
        /// </summary>
        public static string Generic_UnexpectedError {
            get {
                return ResourceManager.GetString("Generic_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is temporarily blocked.
        /// </summary>
        public static string Generic_UserBlocked {
            get {
                return ResourceManager.GetString("Generic_UserBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the user. Please try again.
        /// </summary>
        public static string Generic_UserCreationFail {
            get {
                return ResourceManager.GetString("Generic_UserCreationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve user data.
        /// </summary>
        public static string Generic_UserFail {
            get {
                return ResourceManager.GetString("Generic_UserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is inactive. Please contact the system administrator.
        /// </summary>
        public static string Generic_UserInactive {
            get {
                return ResourceManager.GetString("Generic_UserInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Already Used, trye again.
        /// </summary>
        public static string Generic_UserNameAlreadyUsed {
            get {
                return ResourceManager.GetString("Generic_UserNameAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is active but has no role assigned.
        /// </summary>
        public static string Generic_UserNoRoleAssigned {
            get {
                return ResourceManager.GetString("Generic_UserNoRoleAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A transaction is already active.
        /// </summary>
        public static string Transaction_AlreadyActive {
            get {
                return ResourceManager.GetString("Transaction_AlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active transaction to commit.
        /// </summary>
        public static string Transaction_NoActiveToCommit {
            get {
                return ResourceManager.GetString("Transaction_NoActiveToCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active transaction to rollback.
        /// </summary>
        public static string Transaction_NoActiveToRollback {
            get {
                return ResourceManager.GetString("Transaction_NoActiveToRollback", resourceCulture);
            }
        }
    }
}
